// <auto-generated />
using FogachoWebHeladeria;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FogachoWebHeladeria.Migrations
{
    [DbContext(typeof(Data))]
    [Migration("20241126011342_FogachoHeladeriaDB")]
    partial class FogachoHeladeriaDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FogachoWebHeladeria.Models.AF_Helado", b =>
                {
                    b.Property<int>("AF_IdHeladeria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AF_IdHeladeria"));

                    b.Property<int>("AF_Categorias")
                        .HasColumnType("int");

                    b.Property<string>("AF_Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AF_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AF_Queso")
                        .HasColumnType("bit");

                    b.Property<string>("AF_Sabor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AF_IdHeladeria");

                    b.ToTable("AF_Helado");
                });
#pragma warning restore 612, 618
        }
    }
}
